### ISSUE TITLE
Profile still in use?

### ISSUE THREAD

**Issue by p-mq** [CodeBlue/cs314#2]
Hi codeblue!

We, two MD/PhD students from Germany, wanted to start an organisation to share some of our experience getting into quantitative research and computer science, including utility packages and coding templates. This would hopefully help to get more medical folks into the subject.

We fell in love with the idea of naming our organisation codeblue to highlight the two disciplines involved. Since your account has no public activity since 2011 - would you be wiling to release the name?

Thank you so much,
Peter and Till

**Comment by CodeBlueDev** [comment]
Sorry, this account is in use and active although not publicly.
